version: '3.8'

services:
  lightrag:
    build: .
    container_name: lightrag-app
    restart: unless-stopped
    ports:
      - "9621:9621"
    environment:
      - WORKING_DIR=${WORKING_DIR:-/app/data/rag_storage}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-anthropic/claude-3.5-sonnet}
      - VISION_MODEL=${VISION_MODEL:-openai/gpt-4o}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - EMBEDDING_DIM=${EMBEDDING_DIM:-1536}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - POSTGRES_URI=${POSTGRES_URI}
    volumes:
      - ./data:/app/data
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coolify:
    external: true
    name: coolify
