version: '3.8'

services:
  lightrag:
    build: .
    restart: unless-stopped
    ports:
      - "9621:9621"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    environment:
      - WORKING_DIR=${WORKING_DIR}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - VISION_MODEL=${VISION_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - EMBEDDING_DIM=${EMBEDDING_DIM}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - POSTGRES_URI=${POSTGRES_URI}
    volumes:
      - ./app/data:/app/data
      - lightrag-cache:/root/.cache
    tmpfs:
      - /tmp:size=2G,mode=1777
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  lightrag-cache:
    driver: local

networks:
  coolify:
    external: true
    name: coolify
